[package]
name = "grenad"
description = "Shrinkable simple sorted string table"
version = "0.2.0"
authors = ["Kerollmops <clement@meilisearch.com>"]
repository = "https://github.com/Kerollmops/grenad"
documentation = "https://docs.rs/grenad"
edition = "2018"
license = "MIT"

[dependencies]
bytemuck = { version = "1.7.0", features = ["derive"] }
byteorder = "1.3.4"
flate2 = { version = "1.0", optional = true }
log = "0.4.11"
snap = { version = "1.0.0", optional = true }
tempfile = "3.1.0"
zstd = { version = "0.5.1", optional = true }

[dev-dependencies]
quickcheck = "0.9"

[target.'cfg(target_os = "linux")'.dependencies]
nix = "0.19.0"

[features]
default = ["zlib", "snappy", "zstd"]
snappy = ["snap"]
zlib = ["flate2"]
